package com.gymflow.app;
import android.content.Intent; import android.os.Bundle; import android.widget.*; import androidx.appcompat.app.AppCompatActivity; import org.json.*;
public class MainActivity extends AppCompatActivity {
 private LinearLayout root; private TextView gymTitle,memberCard,paymentCard,equipmentCard;
 @Override protected void onCreate(Bundle b){super.onCreate(b);if(!Session.logged(this)){startActivity(new Intent(this,LoginActivity.class));finish();return;}build();}
 private void build(){ScrollView scroll=new ScrollView(this);root=Ui.page(this);scroll.addView(root);root.addView(Ui.title(this,"GymFlow"));gymTitle=Ui.subtitle(this,"Panel administrador · online");root.addView(gymTitle);memberCard=Ui.card(this,"… socios activos","Cargando datos online");root.addView(memberCard);paymentCard=Ui.card(this,"$ … cobrados","Pagos registrados");root.addView(paymentCard);equipmentCard=Ui.card(this,"… equipos cargados","Las rutinas usan tus máquinas reales");root.addView(equipmentCard);add("Socios",MembersActivity.class);add("Pagos y cuotas",PaymentsActivity.class);add("Equipamiento del gimnasio",EquipmentActivity.class);add("Rutinas",RoutinesActivity.class);add("Progreso de socios",ProgressActivity.class);add("Profesores",TeachersActivity.class);add("Configuración",SettingsActivity.class);Button out=Ui.button(this,"Cerrar sesión");out.setOnClickListener(v->{out.setEnabled(false);Cloud.signOut(this,(code,body)->{startActivity(new Intent(this,LoginActivity.class));finish();});});root.addView(out);setContentView(scroll);}
 private void add(String s,Class<?> c){Button b=Ui.button(this,s);b.setOnClickListener(v->startActivity(new Intent(this,c)));root.addView(b);}
 private void load(){Cloud.get(this,"gf_gyms","select=id,name&owner_id=eq."+Session.uid(this),(c,b)->{try{JSONArray a=new JSONArray(b);if(a.length()==0){startActivity(new Intent(this,SetupGymActivity.class));finish();return;}String n=a.getJSONObject(0).optString("name","Mi gimnasio");gymTitle.setText(n+" · Panel administrador");getSharedPreferences("gymflow",0).edit().putString("gym_name",n).apply();}catch(Exception ignored){}});Cloud.get(this,"gf_members","select=status&owner_id=eq."+Session.uid(this),(c,b)->{try{JSONArray a=new JSONArray(b);int n=0;for(int i=0;i<a.length();i++)if("Activo".equals(a.getJSONObject(i).optString("status")))n++;memberCard.setText(n+" socios activos\nGestión de socios y planes");}catch(Exception e){memberCard.setText("Sin datos\nNo se pudieron cargar socios");}});Cloud.get(this,"gf_payments","select=amount&owner_id=eq."+Session.uid(this),(c,b)->{try{JSONArray a=new JSONArray(b);long n=0;for(int i=0;i<a.length();i++)n+=a.getJSONObject(i).optLong("amount");paymentCard.setText("$ "+n+" cobrados\nPagos registrados online");}catch(Exception ignored){}});Cloud.get(this,"gf_equipment","select=id&owner_id=eq."+Session.uid(this),(c,b)->{try{equipmentCard.setText(new JSONArray(b).length()+" equipos cargados\nLas rutinas usan tus máquinas reales");}catch(Exception ignored){}});}
 @Override protected void onResume(){super.onResume();if(root!=null&&Session.logged(this))load();}
}
