package com.gymflow.app;
import android.app.AlertDialog; import android.os.Bundle; import android.widget.*; import androidx.appcompat.app.AppCompatActivity; import org.json.*; import java.text.NumberFormat; import java.util.*;
public class PaymentsActivity extends AppCompatActivity{
 private LinearLayout list; private TextView total;
 @Override protected void onCreate(Bundle b){super.onCreate(b);ScrollView s=new ScrollView(this);LinearLayout r=Ui.page(this);s.addView(r);Ui.backHeader(this,r,"Pagos y cuotas");total=Ui.card(this,"$ 0","Total cobrado registrado online");r.addView(total);Button add=Ui.button(this,"+ Registrar pago");add.setOnClickListener(v->loadMembersAndDialog());r.addView(add);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);r.addView(list);load();setContentView(s);}
 private String money(long n){return NumberFormat.getCurrencyInstance(new Locale("es","AR")).format(n);}
 private void load(){list.removeAllViews();Cloud.get(this,"gf_payments","select=id,member_name,amount,method,paid_at&owner_id=eq."+Session.uid(this)+"&order=paid_at.desc",(c,b)->{try{JSONArray a=new JSONArray(b);long sum=0;for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);sum+=o.optLong("amount");list.addView(Ui.card(this,o.optString("member_name")+" · "+money(o.optLong("amount")),o.optString("method")));}total.setText(money(sum)+"\nTotal cobrado registrado online");if(a.length()==0)list.addView(Ui.card(this,"Sin pagos","Registrá el primer pago."));}catch(Exception e){list.addView(Ui.card(this,"Error",Cloud.err(b)));}});}
 private void loadMembersAndDialog(){Cloud.get(this,"gf_members","select=id,full_name&owner_id=eq."+Session.uid(this)+"&order=full_name.asc",(c,b)->{try{JSONArray a=new JSONArray(b);if(a.length()==0){Toast.makeText(this,"Primero agregá un socio",Toast.LENGTH_LONG).show();return;}String[] names=new String[a.length()];String[] ids=new String[a.length()];for(int i=0;i<a.length();i++){names[i]=a.getJSONObject(i).optString("full_name");ids[i]=a.getJSONObject(i).optString("id");}LinearLayout box=Ui.page(this);Spinner member=Ui.spinner(this,names);box.addView(member);EditText amount=Ui.input(this,"Importe");amount.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);box.addView(amount);Spinner method=Ui.spinner(this,new String[]{"Transferencia","Efectivo","Mercado Pago","Otro"});box.addView(method);new AlertDialog.Builder(this).setTitle("Registrar pago").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",(d,w)->{try{int pos=member.getSelectedItemPosition(),amt=Integer.parseInt(amount.getText().toString().trim());JSONObject o=new JSONObject();o.put("owner_id",Session.uid(this));o.put("member_id",ids[pos]);o.put("member_name",names[pos]);o.put("amount",amt);o.put("method",method.getSelectedItem().toString());Cloud.post(this,"gf_payments",o,(cc,bb)->{if(cc>=200&&cc<300)load();else Toast.makeText(this,Cloud.err(bb),Toast.LENGTH_LONG).show();});}catch(Exception e){Toast.makeText(this,"Ingresá un importe válido",Toast.LENGTH_SHORT).show();}}).show();}catch(Exception e){Toast.makeText(this,"No se pudieron cargar socios",Toast.LENGTH_LONG).show();}});}
}
